---
# Variables can be set from the shell: `DOCKERTAG=foo docker-compose build`
# or from a .env file. See docker-compose documentation for details
# Variable DOCKERUSER should be set to your dockerhub user
# Alternatively, use a docker registry url as the image name
services:
  ## Image runtime service
  ## This can be used to add volume mounts or pass environment variables
  ## Todo: make a service which can use the container interactively
  openface:
    container_name: openface
    build:
      context: .
      dockerfile: docker/Dockerfile
      args:
        - TARGETARCH=${TARGETARCH}
    image: "${DOCKERUSER}/openface:${DOCKERTAG}"
    devices : 
      - /dev/video0:/dev/video0
    ports:
      - "8000:8000"
    tty: true
    environment:
      LC_ALL : C.UTF-8
      LANG : C.UTF-8
    
    # command: bash
    command: ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]
  
...